from tkinter import *
from tkinter import ttk	
def y():
	t.pack()
	l     =     Etiket ( w , text    =    "oyunu bilmiyorsan https://kirmiziyesilimpostorkurallari.wordpress.com/'a gir!" )
	l.pack()
w = Tk()
w.title("HELL ON MY MİND")
w.geometry("500x500")
m = ttk.Notebook(w)
m.pack()
f = Frame(m,width="500",height="500",bg="red")
f.pack()
s = Frame(m,width="500",height="500",bg="green")
s.pack()
g = Label(f,text="İMPOSTOR OLMAK ÖYLE KOLAY DEĞİL AMA\n BAŞARILI BİR İMPOSTOR ÖLDÜRMESİNİ BİLİR!",bg="red")
g.pack()
h = Label(s,text="YEŞİL DAHA BOKUNU TEMİZLEYEMEZ",bg="green")
h.pack()
m.add(f,text="KIRMIZI İMPOSTOR")
m.add(s,text="YEŞİL İMPOSTOR")
t = Label(w,text="OYUN BAŞLADI!!!")
b = Button(w,text="BAŞLA",bg="red",fg="black",command=y)
b.pack()
w.mainloop()
